### David Ross Hall --- created on 2022-11-22

### Loose plots for thesis defence talk

```{r}
library(ggplot2)


# plot of DBP cancer data.
df <- readr::read_csv("data/hrudey_2009_waterResearch.csv")

colors <- c("#499167", "#758BFD", "#FF8600")

o <- ggplot(data = df,
       aes(x = fct_reorder(ref,adj_or),
           y = adj_or,
           ymin = ci_95_low,
           ymax = ci_95_high,
           colour = sex
       )) +
  geom_hline(yintercept = 1, size=1) +
  geom_errorbar(color = "black",
                width = 0.3) +
  geom_point(size=4) +
  #facet_wrap(~sex, ncol = 1, scales = "free_y") +
  scale_color_manual(values = colors) +
  theme_bw() +
  theme(legend.position = "right",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent"),
        text = element_text(size = 10)
  ) +
  labs(y = "Odds Ratio (1.0 = no association)",
       x = "",
       colour = "Sex") +
  scale_y_continuous(trans = "log2",
                     breaks = c(0.5, 1, 2, 4, 8)) +
  coord_flip(ylim = c(0.5, 8))

o
```

```{r, eval = FALSE}

ggsave(filename = "images/03-DBP/dbp_epi.png",
       plot = o,
       units = "in", 
       width = 6,
       height = 4, 
)

```

## PCB 77 bird tox
```{r}
library(tidyverse)

tox <- read_csv("data/pcb77_bird_tox.csv")

p <- ggplot(data = tox,
       aes(x = dose,
           y = mortality,
           colour = species)) +
  geom_point(size = 3, alpha = 0.8) +
 #   scale_x_log10(
 #    breaks = scales::trans_breaks("log10", function(x) 10^x),
 #    labels = scales::trans_format("log10", scale::)
 #  #  labels = scales::label_number(scale_cut = scales::cut_long_scale())
 # ) +
  scale_x_log10() +
  annotation_logticks(sides = "b",
                      short = unit(.5,"mm"),
                      mid = unit(3,"mm"),
                      long = unit(4,"mm")
) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(x = "PCB 77 Dose (ng/g)",
       y = "Avian Embryo Mortality ") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        text = element_text(size = 16) )

p2 <- p +
  # Tern and waterfowl annotation
  geom_curve(
  aes(x =  4000, y = 19, xend = 5000, yend = 5),
  colour = "black",
  curvature = -0.15,
  arrow = arrow(length = unit(0.03, "npc"))
) +
  annotate("text", x = 4100, y = 25.5, hjust = 1, label = "herring gull\n& duck") +
  
  # Chicken annotation
  geom_curve(
  aes(x =  50, y = 83, xend = 24, yend = 98),
  colour = "black",
  curvature = 0.2,
  arrow = arrow(length = unit(0.03, "npc"))
) +
  annotate("text", x = 90, y = 80, hjust = 1, label = "chicken") +
  # Adjusting legend beaks
  scale_colour_discrete(breaks=c("chicken", "pheasant", "turkey", "duck", "herring gull"))

p2
```

```{r, eval = FALSE}
ggsave(filename = "images/01-intro/pcb77_toxV2.png",
       plot = p2, 
       units = "in", 
       height = 4, 
       width = 6)
```

## Ahr binding plot

-   Karchner et al. PNAS 2009

```{r}
library(tidyverse)
# data extracted from Fig. 4D using webplot digitizer
ahr <- data.frame("variant" = c("Chicken", "Tern", "Tern T258A", "Tern V3251I", "Tern A381S"),
                  "ahr_binding" = c(100, 21, 16.5, 65.5, 81.0))
point_colour <- "#3453A5"

q <- ggplot(data = ahr, 
       aes(x = fct_reorder(variant, ahr_binding), 
           y = ahr_binding)) +
  # geom_bar(stat = "identity") +
  # geom_hline(yintercept=seq(25, 100, 25), col="white", lwd=1) +
  geom_segment(aes(x = fct_reorder(variant, ahr_binding), 
                   xend = fct_reorder(variant, ahr_binding),
                   y = 0, 
                   yend = ahr_binding),
               colour = point_colour) +
  geom_point(size=5, colour = point_colour) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  theme_classic(base_size = 16) +
  theme(legend.position = "none",
        #text = element_text(size = 12)) +
        ) +
  labs(x = "",
       y = "Percent TCDD binding\nvs. Chicken AHR") +
  coord_flip()

q2 <- q +
  # Tern T258A
  geom_curve(
    aes(x =  1.4, y = 82, xend = 0.9, yend = 22),
    colour = "black",
    curvature = -0.3,
    arrow = arrow(length = unit(0.03, "npc"))
) +
  # Tern V3325I
    geom_curve(
    aes(x =  2.6, y = 82, xend = 3, yend = 70),
    colour = "black",
    curvature = 0.4,
    arrow = arrow(length = unit(0.03, "npc"))
) +
  # Tern A381S
    geom_curve(
    aes(x =  2.6, y = 82, xend = 3.8, yend = 83),
    colour = "black",
    curvature = 0.4,
    arrow = arrow(length = unit(0.03, "npc"))
) +
  annotate("text", x = 2, y = 100, hjust = 1, label = "Tern amino acid\nchanged to chicken\ncounterpart") 

q2
```
```{r, eval = FALSE}

ggsave(filename = "images/01-intro/ahr_binding_plot.png",
      plot = q2, 
      units = "in", 
      width = 5, 
      height = 4)

```
